### ISSUE TITLE
how to prevent creation of DB subnet

### ISSUE THREAD

**Issue by lqueryvg** [smoketurner/serverless-vpc-plugin#1]
Hi,

Is there a way to prevent the plugin from creating a DB subnet ?

I have no RDS and I only want 2 subnets: private and public. My lambda will run in the private subnet and route internet traffic via NAT with EIP in the public subnet.

In the interest of keeping my AWS resource config minimal, simple and secure I'd rather it didn't create the DB subnet.

My test config is below, and event when I specifying only one subnet, it creates three (db, app and public):

In `provider`:

    vpc:
      securityGroupIds:
        - Ref: LambdaExecutionSecurityGroup
      subnetIds:
        - Ref: AppSubnet1

In `custom`:

    vpcConfig:
      cidrBlock: "10.0.0.0/16"
      useNatGateway: true
      zones:
        - eu-west-1a
      services:
        - kms
        - secretsmanager

Thanks in advance.

**Comment by jplock** [comment]
The DBSubnet won’t be created unless there are at least two AZ’s specified.

**Comment by lqueryvg** [comment]
Yes, that's what I'm seeing - 3 subnets.

> The DBSubnet won’t be created unless there are at least two AZ’s specified.

Yeah I can see that in the code. And yet, with 1 AZ, the DB subnet is still getting created... ?
I've tried tearing the whole thing down and starting again. Same result. Bizarre.

Besides, I probably want to configure 2 AZs for, ahem, availability.

It seems that I'll always get a DB subnet. Would be nice to have an option to stop that being created.

**Comment by jplock** [comment]
ooh, sorry, I thought you meant the RDSSubnetGroup, not the DB subnet.  You are correct in that regardless of how many AZ's you specify, the DB subnet will still be created.

**Comment by lqueryvg** [comment]
Thanks for the advice.

My lambda needs to access to internet though - I need the NAT gateway.
Although I didn't realise I would need more than one for availability - I thought the "service" might just magically stay available for me. I should have known better. But for my use case I think I can manage with 1 for now.

**Comment by jplock** [comment]
@lqueryvg I just pushed up #2 to address this.  Would you mind testing it out by updating your package.json to:

```
"serverless-vpc-plugin": "git://github.com/smoketurner/serverless-vpc-plugin.git#jp-skip-db
```

and setting `skipDbCreation: true` in the `custom.vpcConfig` section?

**Comment by lqueryvg** [comment]
Cool - I've tested that. It works.

I have another question (I can put it on a separate ticket if you want?)...
My whole purpose for creating a custom VPC + NAT is to have a fixed EIP address which 3rd parties can whitelist.

I'd like to be able to protect the EIP from an accidental "sls remove".
It would be great if I could specify the EIP externally to this stack.
I.e. I'd like to be able to specify the EIP as an external resource - which I'll create elsewhere. Therefore creating or removing this stack won't change my EIP address.

**Comment by jplock** [comment]
@lqueryvg when you say 3rd parties, do you mean the calls your lambda is making outbound from the VPC, you want 3rd parties to be able to whitelist the source of your lambda traffic.  Or do you want 3rd parties to be able to whitelist the IP they use to communicate to your lambda (through an API Gateway, I'm assuming).

**Comment by lqueryvg** [comment]
@jplock I mean the former. I.e. the outbound calls from my lambda from the VPC to 3rd parties. I want the outbound calls to come from the same fixed IP that the 3rd parties can whitelist.

It would be annoying if that IP ever changes, because then the 3rd parties all need to update their whitelist - hence I'd like to protect it, by not letting it get deleted by the stack.

**Comment by lqueryvg** [comment]
That would work. As long as on removal it remembers (or can tell from the config) that it should not delete the IP if it didn't create it in the first place... I guess the AWS stack would prevent that from happening ?

Why an array though of EIPs though ? Can a NAT gateway have more than one EIP ? I thought it could only have one ??

**Comment by jplock** [comment]
NAT Gateways can only use a single EIP. If the EIP wasn’t created by the CloudFormation template, then it won’t be removed if you remove your app. Redeploys won’t change the EIP if CloudFormation does create them. You could just provision as normal then tell the 3rd parties what the EIPs are. The EIP’s wouldn’t change unless you torn everything down.

**Comment by jplock** [comment]
Another easier option might be to introduce a boolean flag to add Retain to the CloudFormation template under the EIP's so they won't be removed if you do `sls remove`.  If you then do another deploy though, I'm not sure they would get re-associated to the NAT Gateways or not.  I'd need to test that.

**Comment by lqueryvg** [comment]
I don't think the EIP would get re-associated when you do another deploy - I don't see how the new stack could know which EIP to use.
