### ISSUE TITLE
How to access VPC generated in other serverless.yml?

### ISSUE THREAD

**Issue by MikeSpitz** [smoketurner/serverless-vpc-plugin#102]
Hi,

I've got the following set up:

infrastructure/serverless.yml
apiLambda/serverless.yml

infrastructure/serverless.yml includes the RDS/IAM.yml like in your example.

Only the infrastructure.yml has the vpc plugin installed but I'm struggling to get apiLambda/serverless.yml to connect to the other VPC. I have outputExports set to true and tried setting:
```
provider:
  vpc: STACK-NAME-VPC
```
But when the lambda is deployed I can see that the VPC hasn't been connected.

Any ideas on how I can get to fix this would help me out a lot! Let me know if I can help by giving anymore information

**Comment by MikeSpitz** [comment]
Sorry! I'm sure I'm being an idiot. I haven't been able to find out how I can get the subnet ids within cloudformation with just the subnet group reference.

I looked into the code and see that the subnet ids aren't being outputted. IN my mind that means that at present we cannot reference via subnet id specifically? Doing so would allow us to set which subnets we want lambdas (in other serverless.yml files) to be included with.

Happy to try and open a PR and do so just rather not do work if there's a workaround at present :)

**Comment by jplock** [comment]
We can also exports the subnet IDs if that fixes the issue.  Happy to review a PR.

**Comment by roni-frantchi** [comment]
@jplock I'm working on a PR to append subnet IDs to outputs (and export).  
Will open it soon
