### ISSUE TITLE
Use existing EIP instead of creating one.

### ISSUE THREAD

**Issue by corupta** [smoketurner/serverless-vpc-plugin#1034]
Hi, when creating Nat Gateway, I want to be able to use an existing EIP.
I couldn't find out how to do it, so I've forked the lib and implemented it for my use.
If it's okay, I'd like to open a PR.

Thanks, in advance.

**Comment by buddhaCode** [comment]
Nice Feature. I need exactly this, too.
@corupta Did you make an PR?

**Comment by buddhaCode** [comment]
@jplock Can you reopen the issue?

**Comment by buddhaCode** [comment]
@jplock I tried to open a PR for @corupta changes. But I got an error: `Pull request creation failed. Validation failed: must be a collaborator`
How can I become a collaborator?

**Comment by jplock** [comment]
You need to fork this repository and submit your PR from your fork.

**Comment by caosborne89** [comment]
I could also use this feature.

**Comment by jplock** [comment]
I'm going to close this issue. I'm going to archive this repo as I no longer use this plugin.
