### ISSUE TITLE
Way to opt a function out of VPC config

### ISSUE THREAD

**Issue by disbelief** [smoketurner/serverless-vpc-plugin#106]
Hi there,

I was wondering if there's a way to opt specific functions out of the global VPC config that this plugin creates?

Use case is: I have some functions that are replicated to Lambda @ Edge, and thus the source functions are not allowed to be inside a VPC.

What I'm doing currently is adding the following "empty" VPC config to the function:

```YAML
vpc:
  securityGroupIds: []
  subnetIds: []
```

This seems to work sometimes (haven't fully tested it), but is there maybe a better way?

**Comment by jplock** [comment]
What I've done in the past is have a separate project specifically for my lambda @ edge functions pinned to us-east-1, and then only put this plugin into my main project.

**Comment by disbelief** [comment]
Hrm not ideal for me as I have a lot of shared modules/business logic between my edge and non-edge lambdas.

**Comment by jplock** [comment]
This might be more of a framework issue as I don’t know how to have some functions associated to a VPC and others not
