### ISSUE TITLE
WebBucket.Arn reference invalid

### ISSUE THREAD

**Issue by johnny-walt17** [smoketurner/serverless-vpc-plugin#1109]
Hello guys, after installing this plugin and adding the necessary serverless yml configs. Upon deploy i'm getting this error

<img width="878" alt="Screenshot 2023-04-17 at 5 03 19 PM" src="https://user-images.githubusercontent.com/111729830/232438948-998fc7e0-a853-40c5-bff4-76614810b271.png">

I tried searching related `WebBucket.Arn` error into the docs and references but I found it in one of the code blocks inside https://github.com/smoketurner/serverless-vpc-plugin/blob/master/src/flow_logs.js at line 95 & 98. 

I immediately thought that the code might needed to be changed here, this should've been `LogBucket` instead of the WebBucket; which causes the error.

Please let me know your thoughts!

**Comment by jplock** [comment]
Yes you are correct, it should be LogBucket

**Comment by jplock** [comment]
Fixed in https://github.com/smoketurner/serverless-vpc-plugin/commit/27e71e962e88cf7add693ce0be1a9e829e4fc1ad and published as v1.0.6
