### ISSUE TITLE
Incompatible with provider option `disableRollback`

### ISSUE THREAD

**Issue by mwillbanks** [smoketurner/serverless-vpc-plugin#1221]
If there is a new AMI available and `disableRollback` is set to `true`, this plugin will cause an error: 

```
UPDATE_FAILED: NatInstance (AWS::EC2::Instance)
Replacement type updates not supported on stack with disable-rollback.
```

**Comment by jplock** [comment]
I no longer use this plugin. I’d be willing to review a pull request

**Comment by jplock** [comment]
I'm going to close this issue. I'm going to archive this repo as I no longer use this plugin.
