### ISSUE TITLE
route table rtb-x and network gateway igw-x belong to different networks

### ISSUE THREAD

**Issue by homes2001** [smoketurner/serverless-vpc-plugin#147]
# Problem

Version: 0.9.3

Configuration is empty:

```
plugins:
  - serverless-vpc-plugin

custom:
  vpcConfig:
```

With the above configuration, running  `serverless deploy` fails with:

```
  An error occurred: PublicRoute2 - route table rtb-03701c7a6171e6432 and network gateway igw-0138227911f6b43af belong to different networks (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 12b44f4c-f15b-4217-ab15-3ffc888c9d5f).
```

# Fix

```
diff /tmp/old.js node_modules/serverless-vpc-plugin/src/vpc.js
195a196
>     DependsOn: ['InternetGatewayAttachment'],
```

**Comment by jplock** [comment]
Can you submit a pull request to review?

**Comment by solsglasses** [comment]
@homes2001 can you submit a PR?

**Comment by solsglasses** [comment]
Until this is perm fixed, here is a workaround:

Create the stack initially with `createNatGateway: 0`. After it is created, you can then set the value to whatever quantity you desire and update the stack.
