### ISSUE TITLE
can't exclude package folders

### ISSUE THREAD

**Issue by mikestaub** [smoketurner/serverless-vpc-plugin#170]
When using this plugin, the default package exclude option no longer works as described here:

https://serverless.com/framework/docs/providers/aws/guide/packaging/

This is my config, but src is still being included in the artifact.

```
package:
  exclude:
    - src/**
```

**Comment by jplock** [comment]
Is that an issue with this plugin or with Serverless?

**Comment by mikestaub** [comment]
I assume this plugin as this is the only plugin I am using, I will confirm by trying it with this plugin disabled.

**Comment by mikestaub** [comment]
I was able to resolve the issue by following this comment: https://forum.serverless.com/t/package-excludes-do-not-seem-to-work/2314/11
