### ISSUE TITLE
What IAM permissions required?

### ISSUE THREAD

**Issue by levz0r** [smoketurner/serverless-vpc-plugin#184]
Hi, thanks for this awesome plugin!

Is it possible to obtain the list of all the required IAM permissions in order to fully deploy a serverless solution with VPC enabled?

Thank you.

**Comment by jplock** [comment]
That’s been a longtime ask of the Serverless project in general (if you look their issues list). It’s a very wide list of actions to cover all of the possible functionality. Unfortunately, AdministratorAccess may be the best bet for now. I’ll try to link to the related issues.
