### ISSUE TITLE
How to use a fix EIP that does not change when re-creating the stack?

### ISSUE THREAD

**Issue by porschberg** [smoketurner/serverless-vpc-plugin#251]
Hi,

I have the problem that the EIP address has another value when I drop and recreate the stack.
I want use the same IP any time I have to recreate the stack.

I have in my infrastructure ec2-instances with EIPs. Could I assign this IP-addresses here too?

I see in natgw.js

```
function buildEIP(position) {
  const cfName = `EIP${position}`;
  return {
    [cfName]: {
      Type: 'AWS::EC2::EIP',
      Properties: {
        Domain: 'vpc'
      },
    },
  };
}
```

Could I add another line

```
function buildEIP(position) {
  const cfName = `EIP${position}`;
  return {
    [cfName]: {
      Type: 'AWS::EC2::EIP',
      Properties: {
        Domain: 'vpc',
        InstanceId : 'logical-name-of-myec2-instance'
      },
    },
  };
}
```

or is this idea totally wrong? 

In https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html 
I see a parameter "PublicIpv4Pool" but I do not own a address pool. However I could create a further EIP in aws-console. But how could I assign/use this EIP in this stack?

**Comment by aldex32** [comment]
I am interested on this as well.

**Comment by porschberg** [comment]
Yep, but idea above does not work. I tried it. 

There is a parameter 'PublicIpv4Pool' see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html
but I do not see how to assign a EIP from aws-pool?!
