### ISSUE TITLE
Can't create Bastion

### ISSUE THREAD

**Issue by isaacl** [smoketurner/serverless-vpc-plugin#258]
When I try to use `createBastionHost` and `bastionHostKeyName`, deploy fails with

`BastionAutoScalingGroup | CREATE_FAILED`

**Comment by jplock** [comment]
Is there any more information as to why it failed?

**Comment by isaacl** [comment]
if you know where to look I can definitely copy logs..  but I don't see
anything in the cloudformation page :-\

Isaac

**Comment by isaacl** [comment]
my config:
```
  vpcConfig:
    createBastionHost: true
    bastionHostKeyName: BastionKey-${self:provider.stage}
    createNatGateway: 1
    cidrBlock: '10.0.0.0/16'
    createDbSubnet: true
    services:
      # although dbinit calls secretsmanager, it is only run on deploy
      # and calls can also go through NAT gateway. (both cost $$/hr)
      []
    subnetGroups:
      - rds```

**Comment by jplock** [comment]
Does the KeyPair already exist?  It needs to and this stack doesn't create it for you.

**Comment by isaacl** [comment]
yes, keypair exists

Isaac

**Comment by isaacl** [comment]
In EC2 -> Auto Scaling Groups -> Activity History I found this:
```
Failed |  Max spot instance count exceeded.
```
I don't have other spot instances on the account, so not sure why that limit is being hit.  But I've requested a service limit increase for the limit and hopefully that solves this issue.

Next stop is trying to get a PR for egress gateway!

**Comment by isaacl** [comment]
btw: would it be possible to have the bastion min instances go to 0 and only launch on demand?

**Comment by jplock** [comment]
We could have it go to zero but I’m not sure trying to SSH to the host would make a suitable scale up criteria. Also, if you need to use a bastion host, it usually means you need to get into an instance quickly to fix something. 

I was actually considering removing this functionality in favor of Systems Manager Session Manager instead.

**Comment by isaacl** [comment]
I'm not sure bastion is correct for me, I only needed to temporarily connect to my RDS using psql.  So maybe your alternative works better anyway

**Comment by isaacl** [comment]
from AWS support
> I am happy to inform you that we have increased the default limit to 4 t2.micro EC2 Spot Instances for the Northern Virginia region.
