### ISSUE TITLE
Requesting a new Output: All `AppSubnet` IDs as a single string

### ISSUE THREAD

**Issue by solsglasses** [smoketurner/serverless-vpc-plugin#266]
Hey, thanks for this awesome plugin. I use it all the time. Currently, I am including `serverless-vpc-plugin` in the same stack with my microservices. This is great because your plugin automatically added all Subnets and SGs to my functions. However, as I'm sure you know, that takes up about ~70-80 of the 200 resource limit.

So in an attempt to free up some space in my CF templates I am researching how I can separate  VPC resources into a separate serverless.yaml, export the values needed, and declare them in my microservice's `serverless.yaml` files.

You may recommend doing that this way:
```
provider:
  vpc:
    subnetIds:
      - 'Fn::ImportValue': myvpcstack-${opt:stage}-AppSubnet1
      - 'Fn::ImportValue': myvpcstack-${opt:stage}-AppSubnet2
      - ...
```

But I think we can do better than that. We should be able to dynamically discover the subnets that were created, rather than "hardcoding" them. The biggest problem this causes is that not all regions have the same number of AZs(subnets). If I had AppSubnet[1-6] declared, and tried to launch it in an non-US AWS region, it would error because that region only has 3 AZs(subnets) available.

# Feature request
Please create a new stack output, call it `AllAppSubnets`(?), and the value should be all `AppSubnets{i}` as a single string separated by commas. In `us-east-1` this would have 6 values. E.g. `subnet-1234, subnet-2345, subnet-3456, subnet-4567, subnet-5678, subnet-6789`

# Use case, new code example

This is a common pattern used in `serverless.yaml` for this type of situation:
```
vpc:
  subnetIds:
    "Fn::Split":
      - ","
      - 'Fn::ImportValue': myvpcstack-${opt:stage}-AllAppSubnets
```

**Comment by jplock** [comment]
At "work" we started creating SSM parameters for a lot of the elements provisioned for a VPC under a discoverable SSM parameter path.  I was thinking of doing that in this plugin as well as I like that approach than importing values all over the place.  What's your thoughts on that approach?

**Comment by solsglasses** [comment]
I like SSM, I use it all the time. Especially for configuration data that contains passwords and secrets. However, 2 things:

1. SSM wouldn't work in this scenario for the same exact reason that I am posting about. In the CloudFormation templates there is no way to intelligently/dynamically discover all available subnets that this module created, so you are unable to populate your SSM Parameter with a string of `subnet-1234, subnet-2345,....`
2. Even if #1 was not true, and we could leverage SSM for this, it remains true that CloudFormation Exports/Outputs are very superior to SSM for the use case that I am posting about here

**Comment by jplock** [comment]
@solsglasses I just published `v1.0.0` that includes support for creating SSM parameters for the various subnets.  As an example, if my `service` is called `new-service` and the `stage` is `dev`, the plugin will create these SSM parameters:

- `/SLS/new-service/dev/VPC` which has a type of `String` and is the VPC ID
- `/SLS/new-service/dev/AppSecurityGroup` which has a type of `String` and includes the application security group
- `/SLS/new-service/dev/AppSubnets` which has a type of `StringList` and includes however many application subnets in a comma-delimited list
- `/SLS/new-service/dev/PublicSubnets` which has a type of `StringList` and includes however many public subnets in a comma-delimited list
- `/SLS/new-service/dev/DBSubnets` which has a type of `StringList` and includes however many database subnets in a comma-delimited list

You should then be able to [reference](https://www.serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-using-the-ssm-parameter-store) these in your `serverless.yml` file as:
```
vpc:
  securityGroupIds:
    - ${ssm:/SLS/new-service/dev/AppSecurityGroup}
  subnetIds: ${ssm:/SLS/new-service/dev/AppSubnets~split}
```

**Comment by solsglasses** [comment]
Nice! Thank you! I didn't know about [that ~split trick either](https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-using-the-ssm-parameter-store). That looks great.

**Comment by guyschlider** [comment]
Hey,
Sorry for bumping this one, I'm trying to use the example: 
```
  subnetIds: ${ssm:/SLS/new-service/dev/DBSubnets~split}
```

Problem is that I want to use the StackName as a variable, is it possible? ssm:/ syntax with a ${self:custom..} doesn't work.

If we would export DBSubnets as output that wouldn't be nessacary, what am I missing? :)
