### ISSUE TITLE
possible to modify route table?

### ISSUE THREAD

**Issue by mikestaub** [smoketurner/serverless-vpc-plugin#305]
I would like to setup VPC peering with this plugin

**Comment by jplock** [comment]
Once the route tables are created you can do anything you want to them. What specifically would you like to do?

**Comment by mikestaub** [comment]
Just add a route for VPC peering connection. So I have to create another stack that imports the one generated by this plugin? I don't like modifying stuff in the web console.

**Comment by jplock** [comment]
@mikestaub the plugin adds all of the VPC resources into the stack. You can just add an additional CF template to add the peering connection. Would that work?

**Comment by mikestaub** [comment]
Yes, but I will have to do it after the initial deploy as I don't see a way to reference the resources created by this plugin in the template.

**Comment by jplock** [comment]
@mikestaub no that’s what I’m saying. You can just do ‘!Ref VPC’ in your additional template to reference the VPC created by this plugin if you are using the same stack.

**Comment by mikestaub** [comment]
Ok great, thanks!

**Comment by adamkitain** [comment]
I'm trying to do something similar, @mikestaub, wondering how you got the routes in the route tables in this stack to point to the peering connection? 
Like, I have a peering connection `pcx-...` that is at `10.2.0.0/16`, how do I add that to all the routes created by this stack?
