### ISSUE TITLE
Bastion CIDR block format error

### ISSUE THREAD

**Issue by louisn** [smoketurner/serverless-vpc-plugin#318]
An error occurred: BastionSecurityGroup - CIDR block 208.157.160.147
  /32 is malformed (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue;

**Comment by jplock** [comment]
Can you provide your serverless.yml and package.json?

**Comment by louisn** [comment]
I moved on from that issue so I don't have the artifacts you're
requesting.  I should have posted them initially, my apology.

I attempted to re-create the problem without success.

I worked around the problem by using the forked repo
https://github.com/geoseong/serverless-vpc-plugin which resolved the issue
at that time.

**Comment by jplock** [comment]
Ok I’m going to close this for now.
