### ISSUE TITLE
"Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [LambdaExecutionSecurityGroup] in the Resources block of the template" after updating from 0.10.0 to 1.0.0

### ISSUE THREAD

**Issue by JustFly1984** [smoketurner/serverless-vpc-plugin#329]
rolling back to 0.10.0 resolves an issue

<img width="607" alt="Screenshot 2020-07-25 11 15 45" src="https://user-images.githubusercontent.com/2255993/88454079-f8a1f000-ce96-11ea-9cbf-9934049aea56.png">

Running with `SLS_DEBUG=*` does not help much:

<img width="625" alt="Screenshot 2020-07-25 11 48 57" src="https://user-images.githubusercontent.com/2255993/88454103-1a02dc00-ce97-11ea-8a8e-3330461996a5.png">

**Comment by jplock** [comment]
LambdaExecutionSecurityGroup was renamed to AppSecurityGroup

**Comment by JustFly1984** [comment]
@jplock We have updated LambdaExecutionSecurityGroup to AppSecurityGroup and redeployed, but now any lambdas from outside serverless lost access to RDS.

**Comment by jplock** [comment]
Can you create a new security group ingress or egress rule?

**Comment by JustFly1984** [comment]
We have figured out the issue was on our side.
