### ISSUE TITLE
Add Multi-AZ public and private subnet setup

### ISSUE THREAD

**Issue by siutsin** [smoketurner/serverless-vpc-plugin#35]
Possible to set up a multi-AZ public & private subnet VPC? E.g.:

public 1a subnet,
private 1a subnet,
public 1b subnet,
private 1b subnet,
...

Thanks!

**Comment by jplock** [comment]
That’s possible with this plugin. It will create a Public, Application, and Database (private) subnets spanning the AZ’s in a region.

**Comment by siutsin** [comment]
@jplock thanks, I created an example project to clarify further:

1. Is it possible to auto assign `subnetIds` depends on the region? E.g. `us-east-1` have 6 AZs, and `us-west-2` have 4 AZs. [Reference](https://github.com/siutsin/serverless-vpc-plugin-example/blob/412197dbd4471c15c9bd220664d12a59a3eacf95/serverless.yml#L20)
2. I managed to find the resource via CF console. It will be great if the output resources are documented in the README 👍 . I can send a PR if you prefer.

**Comment by jplock** [comment]
I’ll see if I can automatically add the references to the main vpc configuration

**Comment by jplock** [comment]
@siutsin thanks for the feedback! I created #38 to address some of the issues you raised.

**Comment by siutsin** [comment]
> @siutsin thanks for the feedback! I created #38 to address some of the issues you raised.

Brilliant! Thanks, @jplock for the swiftly update 🥇

**Comment by jplock** [comment]
I published `0.4.0` to NPM with these changes.

**Comment by siutsin** [comment]
Tested and deployed with this [serverless.yml](https://github.com/siutsin/serverless-vpc-plugin-example/blob/master/serverless.yml). All good, this saved my life. Thanks again!
