### ISSUE TITLE
Allow Spot NAT instance

### ISSUE THREAD

**Issue by siutsin** [smoketurner/serverless-vpc-plugin#36]
Sometimes, you don't want to pay for the NATGateway especially in the dev environment :P

**Comment by jplock** [comment]
Would you want to be able to specify your own NAT instance route?

**Comment by jplock** [comment]
Actually, I’m going to make it so you can optionally create a bastion instance and use that as the route destination.

**Comment by siutsin** [comment]
> Would you want to be able to specify your own NAT instance route?

Thanks! Most of my case private subnets across different AZ will route to the same NAT instance only in the dev environment, and I think it is overkill to have multiple NAT instance.

Should use NAT Gateway in production though, but it is good to have a bastion host. 👍

**Comment by jplock** [comment]
@siutsin I just published v0.5.0 which supports a new `createBastionHost` option to create a NAT Instance that allows HTTP/HTTPS traffic from the "Application" subnets to reach the Internet.  Thanks for the suggestion!
