### ISSUE TITLE
NAT instance AMI ID is hardcoded to `us-east-1`

### ISSUE THREAD

**Issue by siutsin** [smoketurner/serverless-vpc-plugin#40]
This is related to #36, the AMI ID in this [line](https://github.com/smoketurner/serverless-vpc-plugin/blob/4021e3f9d17c0d796da50b247787888c289abca9/src/bastion.js#L169) is hardcoded, hence can only bring up from the `us-east-1` region.

**Comment by jplock** [comment]
I realized that after I tagged it.  Please try 0.5.1 which I just published.

**Comment by siutsin** [comment]
Great work again @jplock, thanks. Do you consider routing the DB private subnet to a NAT instance or gateway? I remember that patching the RDS required outgoing traffic.

**Comment by siutsin** [comment]
My bad, this impression may come from self-hosting DB back to the days. Probably not required for the RDS auto minor version upgrade.

**Comment by jplock** [comment]
From what I’ve read, we shouldn’t need a default route on the DB subnets and they are still able to be patched, etc. Please let me know if you experience something different.
