### ISSUE TITLE
Support for DocumentDB

### ISSUE THREAD

**Issue by danielstandby** [smoketurner/serverless-vpc-plugin#577]
Hi,

Are there any plans to include DocumentDB as part of the supported services? Its' CloudFormation needs are very similar to RDS. I think it would be somewhat simple.

Regards

**Comment by jplock** [comment]
@danielstandby sorry just seeing this now. Would you want to submit a PR for review?

**Comment by danielstandby** [comment]
I think I could find some time later in august to do ti

**Comment by jplock** [comment]
@danielstandby Actually, all services should be supported as long as you follow the naming convention

**Comment by danielstandby** [comment]
No it doesn't. For example, plugin code for database subnet groups only considers 'AWS::RDS::DBSubnetGroup'. But DocumentDB will need a resource of type 'AWS::DocDB::DBSubnetGroup'

**Comment by rodrigomata** [comment]
Any plans for supporting this? Trying to use this plugin with DocumentDB but I'm missing the security group that provides access to TCP 27017
