### ISSUE TITLE
Option to assign default security group to lambda function

### ISSUE THREAD

**Issue by phpoenix** [smoketurner/serverless-vpc-plugin#67]
After deployment only Lambda Execution security group is assigned to lambda function. However function cannot connect to ElastiCache in this group. I had to manually add default security group to lambda, and create ElastiCache cluster with default security group in order to connect to redis properly.

It would be nice if we could specify an option to automatically assign vpc's default security group beside LambdaExec security group to lambda function during deployment .

**Comment by jplock** [comment]
In your Elasticache SG, are you able to allow ingress access from the LambdaSecurityGroup? I was able to use that method when connecting to RDS.
