### ISSUE TITLE
Add example project

### ISSUE THREAD

**Issue by jplock** [smoketurner/serverless-vpc-plugin#7]
Add an example project to test IAM access information from within the VPC to S3.  This will help ensure that the NACL, Security Groups, VPC Endpoint and S3 bucket policies all work as designed.

**Comment by jplock** [comment]
Fixed in https://github.com/smoketurner/serverless-vpc-plugin/commit/497f5187c63ba1a94b2b0d393d15444b02220631

**Comment by disbelief** [comment]
A little feedback: would be nice if the example project used more of the features and exports of the `serverless-vpc-plugin`.

For example: setting up an RDS database resource inside the VPC with the subnets, db subnet group, and security groups from the generated VPC.

**Comment by jplock** [comment]
@disbelief fixed in https://github.com/smoketurner/serverless-vpc-plugin/pull/80
