### ISSUE TITLE
Avoid mandatory hardcoded zone names

### ISSUE THREAD

**Issue by nponeccop** [smoketurner/serverless-vpc-plugin#823]
There is a builtin 'Fn::GetAz' function which is enough in most cases to avoid hardcoding AZ names.

**Comment by jplock** [comment]
Can you point me to where the code is doing that? I do try to avoid hard coding whenever possible.

**Comment by nponeccop** [comment]
It gets hardcoded in the `serverless.yml`, namely `custom.vpsConfig.zones`.

If people design multi-zone templates, they tend to use zone indices and zone name lookups, so their file works in any region with at least N zones.

**Comment by jplock** [comment]
The zone names are optional.  If not specified however, the plugin will use all of the available AZs in the region.  Maybe a `zoneCount` parameter would be helpful?
