### ISSUE TITLE
security groups

### ISSUE THREAD

**Issue by sharon-asana** [smoketurner/serverless-vpc-plugin#830]
I need to be able to add new security group rules or alter the one that is created by the plugin
unfortunately the plugin doesn't allow that.

do you have any suggestion how to do that without changing the plugin itself?

I was trying to add resources, but since they are created before the vpc, i don't have the vpc-id

**Comment by phishy** [comment]
I was wondering this same thing.

**Comment by jplock** [comment]
You could reference resources created by this plugin in your own CF templates, such as:

`!Ref VPC`

to get the VPC ID
