### ISSUE TITLE
Create Resource in DBSubnets

### ISSUE THREAD

**Issue by guyschlider** [smoketurner/serverless-vpc-plugin#865]
Hey,

I'm trying to create a resource (ElasticSearch / OpenSearch cluster) within the **DBSubnets** subnet ids

Problem is that In order to read from ssm: I need to hardcode enter the StackName to read DBSubnets from SSM, and it's not available as Output so I can't use it as a **!Ref DBSubnets** 

am I missing something?

**Comment by guyschlider** [comment]
@jplock Hey, sorry for bothering, I'm really stuck with this one, do you know if there is a workaround ?

**Comment by tripper54** [comment]
+1 , I'm trying to create a memoryDB subnet group, but I can't seem to reference the DB subnets as they are not included in the outputs.

**Comment by tripper54** [comment]
Cancel that, I was able to reference via !Ref DBSubnet1 and !Ref DBSubnet2
