### ISSUE TITLE
Optional security settings

### ISSUE THREAD

**Issue by jplock** [smoketurner/serverless-vpc-plugin#9]
Maybe do this in a separate project, but:

* Create a KMS key
* Create a logs 
* Enable CloudTrail
* Enable AWS Config
* Enable VPC flow logs

**Comment by giladno** [comment]
Flow logs would be great, I always have problems trying to find out why I can't access A from B.

As for additional features, would be nice to have an easy option to setup RDS (personally I'm using aurora serverless right now). An extra flag which would setup all security zones and access control for lambda would be great (I can help testing if required)

**Comment by jplock** [comment]
Thanks for the suggestions!  I don't think I want to add support for provisioning RDS or Elasticache natively within this plugin as you could go into the console or use the CLI to provision those within the DB subnet (using the provisioned DB subnet groups).  Even with the Network ACL functionality I added last night, the Lambdas running within the Application subnets should be able to access any databases running within the DB subnets.

My original rational for creating this plugin is doing just that by having a Python-based Lambda function running within a VPC to access a Postgres RDS instance and Redis ElastiCache instance running within the DB subnets.

**Comment by jplock** [comment]
@giladno if you're still using this library, I added VPC flow log support (to S3) in v0.3.0
